CREATE TABLE "accident_reports" (
	"id" serial PRIMARY KEY NOT NULL,
	"title" varchar(255) NOT NULL,
	"report_date" timestamp DEFAULT now(),
	"content" varchar(1000),
	"created_by" varchar(100),
	"contact_name" varchar(100),
	"source_organization" varchar(100),
	"source_contact" varchar(100),
	"reception_method" varchar(100),
	"notes" varchar(1000),
	"responsible_entity" varchar(100),
	"transfer_method" varchar(100),
	"task_opened" boolean DEFAULT false,
	"task_status" varchar(100),
	"task_instructor" varchar(100),
	"event_location" varchar(255),
	"reporter_phone" varchar(50),
	"sub_entities" varchar(255),
	"mission_board_task" boolean DEFAULT false,
	"is_relevant_for_assessment" boolean DEFAULT false,
	"tagav" boolean DEFAULT false,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
